### PR TITLE
Add error information to exceptions

### PR DESCRIPTION
**Pull request by armenzg**
We would raise exceptions with a simple message but without the actual
reason for the error being included.

@djmitche r?

### CODE REVIEW

**Comment by djmitche** [comment]
Good fix, but it causes a test failure:

```
1) FAIL: test_exhaust_retries_try_status_code (test.test_client.TestMakeHttpRequest)

   Traceback (most recent call last):
    test/test_client.py line 242 in test_exhaust_retries_try_status_code
      self.assertEqual('msg', str(err))
   AssertionError: 'msg' != 'msg - {\n    "message": "msg",\n    "test": "works"\n}'
       '\'msg\' != \'msg - {\\n    "message": "msg",\\n    "test": "works"\\n}\'' = '%s != %s' % (safe_repr('msg'), safe_repr('msg - {\n    "message": "msg",\n    "test": "works"\n}'))
       '\'msg\' != \'msg - {\\n    "message": "msg",\\n    "test": "works"\\n}\'' = self._formatMessage('\'msg\' != \'msg - {\\n    "message": "msg",\\n    "test": "works"\\n}\'', '\'msg\' != \'msg - {\\n    "message": "msg",\\n    "test": "works"\\n}\'')
   >>  raise self.failureException('\'msg\' != \'msg - {\\n    "message": "msg",\\n    "test": "works"\\n}\'')
```

**Comment by escapewindow** [comment]
I'm about to create a PR for async code+test generation that will bitrot a lot of things, including this PR.
However, I thought this might be nice to have, and included a fix: https://github.com/escapewindow/taskcluster-client.py/commit/6091196112633a0e5ddf9b970cc5b5924dc786ee

**Comment by djmitche** [comment]
Awesome -- ship it!

**Comment by armenzg** [comment]
Happy Armen :)

**Comment by jhford** [comment]
Looks like we can close this PR out

**Pull request closed without merging**
