### PR TITLE
Update install_requires to allow for newer async_timeout

### PR DESCRIPTION
**Pull request by edmorley**
The breaking change made by `async_timeout` doesn't affect this project, since the only usage is with a non-zero timeout:
https://github.com/aio-libs/async-timeout/blob/master/CHANGES.rst#200-2017-10-09
https://github.com/taskcluster/taskcluster-client.py/blob/888c98f8471ee4ce9ae4445353e99ef1560ec0c4/taskcluster/async/asyncutils.py#L39

~The `six` dependency update has been facilitated by switching to PGPy master, since I'd prefer to not wait any longer for a new release. This can be restored to a PyPI version once a release occurs.~

Refs #87 (but doesn't close it, since there's more work to do).

~This PR unblocks two Treeherder PRs:
mozilla/treeherder#2814
mozilla/treeherder#2891 (will be updated once a new taskcluster client is released)~

### CODE REVIEW

**Comment by edmorley** [comment]
Eugh, setuptools doesn't support the full range of version specifiers in `tests_require`, so a URL can't be used (unless using `dependency_links`, but I think that has side effects even for non-`develop` installs, so probably not worth doing).

The only other solution would be to move `tests_require` to a pip requirements file, and having that used as part of the tox run (this is probably worth doing anyway, to help with being able to use pyup.io in #87 - and would help the testing setup in this repo become a bit more standard compared to other projects). 

However I don't really have the time for all that right now, so I guess I'll just have to hold off until the next PGPy release is made.

**Comment by jhford** [comment]
I agree, we should wait for the release to happen.  I'd rather not depend on a specific commit of a repo in the main release.  Are we able to update async timeout independently?  I'd be happy to update that if it works.

**Comment by edmorley** [comment]
I've revised the PR to just update `async_timeout` only :-)

(The restricted version range for async timeout actually caused gerard-majax breakage the other day due to pip's resolver non-determinism, so would be good to relax it)

**Comment by edmorley** [comment]
@jhford could this be merged?

**Comment by jhford** [comment]
Sorry!  Didn't see your new commit.  Looks good to me

**Comment by edmorley** [comment]
Many thanks :-)

**Pull request merged**
