### PR TITLE
flake8 fixes.

### PR DESCRIPTION
**Pull request by escapewindow**
Passes |flake8 --max-line-length=100 test taskcluster *.py| on the mohawk branch.

### CODE REVIEW

**Comment by djmitche** [comment]
LGTM, deferring to @jhford

**Comment by jhford** [comment]
I was hoping the whitespace changes would've been a single commit independent of the other changes... I'll look at this now.

**Comment by jhford** [comment]
Please also modify test.sh as appropriate to match the code-style changes that are being made.

**Comment by jhford** [comment]
@escapewindow looks good.  I'm going to merge this so that @djmitche is able to start working on his changes.  Please fix the 8-space things and modify test.sh then close this PR.

Thanks for the contribution.

**Comment by escapewindow** [comment]
It looks like

* adding changes to the branch doesn't update this PR
* I added PR #38 but don't have perms to merge
* This PR is merged, so there is no "close" button

So PR #38 is open and ready to merge.

I also have questions about how to get my test run green on my laptop, but I'll put those in an email.

**Pull request merged**
