### PR TITLE
Support steaming download.

### PR DESCRIPTION
**Pull request by askeing**
- remove response.text in util (fix the UnicodeEncodeError when downloading files)
- run response.json only if the headers['content-type'] is json format

### CODE REVIEW

**Comment by jhford** [comment]
The unit tests don't pass with this patch.  Can you make sure that they pass?  Without credentials, you can test everything with `NO_TESTS_OVER_WIRE=1` in your environment.

**Comment by jhford** [comment]
It looks like the`ObjWithDotJson` needs to be updated...

you should be able to run the tests with `make tests`

**Comment by askeing** [comment]
@jhford , I updated the object, thanks for your help :)

**Comment by jhford** [comment]
0.0.21 is on pypi with this change

**Comment by jonasfj** [comment]
@jhford, I think this is bad. It gives and inconsistent interface, doesn't handle retries and can't be reimplemented in the go client.

Note, some artifacts may have content-type JSON.

I suggest we discuss a better approach in bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1184209

It's probably something we can easily add to the reference format.

**Pull request merged**
