### PR TITLE
Fixing missing urllib.parse.quote() import

### PR DESCRIPTION
**Pull request by martiansideofthemoon**

### CODE REVIEW

**Comment by armenzg** [comment]
Hi @martiansideofthemoon you probably need to use @ mentions to get a developer to look at this OR paste the URL of the PR in the bugzilla bug as an attachement (You can paste a URL instead of attaching a file).

**Comment by martiansideofthemoon** [comment]
@armenzg i added the link on Bugzilla

**Comment by escapewindow** [comment]
Ah, I didn't realize the bustage was inside this module.
I merged your patch into my async branch, which is awaiting merge in #49.
https://github.com/escapewindow/taskcluster-client.py/commits/async

**Comment by martiansideofthemoon** [comment]
Thanks @escapewindow :smile: When is that likely to be merged?

**Comment by escapewindow** [comment]
@martiansideofthemoon Hopefully soon?  I don't know of anything blocking it atm.

**Comment by djmitche** [comment]
Merged -- I don't know how to do the release, if that's necessary

**Pull request merged**
