### PR TITLE
fix #51, bug 1267521

### LINKED ISSUE #51: taskcluster.asyncutils shows warnings when installed on py27
@armenzg is hitting this when using `python setup.py develop` in mozci.  This isn't a fatal error, and I've definitely seen worse from other packages:

> `Writing /var/folders/y5/h9c4hgd54rv6ng12ynw3ydw00000gn/T/easy_install-3ixVqN/taskcluster-0.3.0/setup.cfg
Running taskcluster-0.3.0/setup.py -q bdist_egg --dist-dir /var/folders/y5/h9c4hgd54rv6ng12ynw3ydw00000gn/T/easy_install-3ixVqN/taskcluster-0.3.0/egg-dist-tmp-DpHpnm
  File "build/bdist.macosx-10.11-x86_64/egg/taskcluster/asyncutils.py", line 19
    async def makeHttpRequest(method, url, payload, headers, retries=utils.MAX_RETRIES,
            ^
SyntaxError: invalid syntax
`

Setuptools evidently only allows you to include/exclude entire packages.  So while I can exclude `taskcluster.async` (a directory), I can't exclude `taskcluster.asyncutils` (a file.)

I previously ran into issues with a circular import when putting asyncutils under `taskcluster/async`, but I think I've found a way around that.

### PR DESCRIPTION
**Pull request by escapewindow**
@djmitche , @armenzg how does this look?

### CODE REVIEW

**Comment by jhford** [comment]
Looks good to me.

**Comment by jhford** [comment]
python 2.7 tests work for me really well, but when I try to run the py35 tests, either with `make test` or `tox -e py35` I get this:

```
ERROR: invocation failed (exit code 1), logfile: /home/jhford/taskcluster/taskcluster-client.py/.tox/py35/log/py35-1.log
ERROR: actionid: py35
msg: installpkg
cmdargs: [local('/home/jhford/taskcluster/taskcluster-client.py/.tox/py35/bin/pip'), 'install', '/home/jhford/taskcluster/taskcluster-client.py/.tox/dist/taskcluster-0.3.0.zip']
env: <snip>

Processing ./.tox/dist/taskcluster-0.3.0.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/taskcluster.egg-info
    writing requirements to pip-egg-info/taskcluster.egg-info/requires.txt
    writing dependency_links to pip-egg-info/taskcluster.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/taskcluster.egg-info/top_level.txt
    writing pip-egg-info/taskcluster.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/taskcluster.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'taskcluster/async' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-gzgwspvq-build/
```

**Comment by escapewindow** [comment]
Sounds like the error you got running release.sh.  The python used to launch the packaging needs to be py35.  Is that the issue?

**Comment by jhford** [comment]
And now it's working again.  I randomly did `pip install tox --upgrade` and
now it seems to be working.  Being able to run tox seems to be completely
random for me, at least based on my experience so far.

Being able to run the release script is really important, I'll add a new
environment variable `DRYRUN` which if set will skip the mutating actions
and set a bogus VERSION just for testing.

Version 0.3.1 released.

**Comment by armenzg** [comment]
Thanks @escapewindow !

**Pull request merged**
